### ISSUE TITLE
moving of files when text is changed (E484: Can't open file v:null)

### ISSUE THREAD

**Issue by RayZ0rr** [gabrielpoca/replacer.nvim#11]
First of all, awesome plugin for code refactoring.

When changing text, replacer is moving the original file to a different location.

I show a demonstration of this with a copy of replacer.nvim repo in the video below:

https://user-images.githubusercontent.com/96843787/214893358-7f8b4f6d-8991-44ef-98d0-e7f803259017.mp4

**Comment by gabrielpoca** [comment]
@RayZ0rr ty for reporting! I'll have a look

**Comment by gabrielpoca** [comment]
I ended up addressing some other bugs in the code. Can you check if it solved yours?

**Comment by RayZ0rr** [comment]
Thanks for the fast response @gabrielpoca 

The issue seems to be fixed but the quickfix becomes empty after saving.  When I open it again `copen` it shows the quickfix window from previous state (before saving)

**Comment by RayZ0rr** [comment]
Also, really sorry for wasting your time. I have just checked the bug myself with the following command:

1. `nvim --clean -u minimal_replacer.lua`
2. `:fzfLua grep`
3. save
4. `:lua require'replacer'.run()`
5. `%s/save/save_edited/
6. `:w`

I  didn't see the problem happening.

**minimal_replacer.lua**

```lua
-- ignore default config and plugins
vim.opt.runtimepath:remove(vim.fn.expand("~/.config/nvim"))
vim.opt.packpath:remove(vim.fn.expand("~/.local/share/nvim/site"))

-- append test directory
local test_dir = "/tmp/nvim/replacer"
vim.opt.runtimepath:append(vim.fn.expand(test_dir))
vim.opt.packpath:append(vim.fn.expand(test_dir))

-- install packer
local install_path = test_dir .. "/pack/packer/start/packer.nvim"
local install_plugins = false

if vim.fn.empty(vim.fn.glob(install_path)) > 0 then
    vim.cmd("!git clone https://github.com/wbthomason/packer.nvim " .. install_path)
    vim.cmd("packadd packer.nvim")
    install_plugins = true
end

local function check_clean()
  for _, arg in ipairs(vim.v.argv) do
    if arg == '--clean' then
      vim.g.loaded_remote_plugins = 1
      return
    end
  end
end
check_clean()

local packer = require("packer")

packer.init({
    package_root = test_dir .. "/pack",
    compile_path = test_dir .. "/plugin/packer_compiled.lua",
})

-- install plugins
packer.startup(function(use)
    use("wbthomason/packer.nvim")
    use {
      'gabrielpoca/replacer.nvim',
      commit = "e06a955104ffabac839be7a2b00a3e10e8f59e16"
    }
    use {
      'ibhagwan/fzf-lua',
      -- optional for icon support
      requires = { 'nvim-tree/nvim-web-devicons' }
    }

    if install_plugins then
        packer.sync()
    end
end)

local ok, replacer = pcall(require, "replacer")
if ok then
  vim.keymap.set('n','<Leader>qf', replacer.run, { desc = "qf replacer activate", nowait = true, silent = true })
end
```

**Comment by RayZ0rr** [comment]
Maybe it's not a waste of time after all. I found the issue causing configuration in my settings.

It's this one:
`vim.opt.autochdir = true`

I also confirmed it by adding this to the **minimal_replacer.lua` file pasted above.

**Comment by RayZ0rr** [comment]
I have compared this with [quickfix-reflector.vim](https://github.com/stefandtw/quickfix-reflector.vim/) using a similar config as the minimal vimrc

The problem doesn't happen when using that plugin. I think one difference between these two plugins might be the existence of an extra newline at the end of quickfix buffer in replacer.nvim ?

```lua
-- ignore default config and plugins
vim.opt.runtimepath:remove(vim.fn.expand("~/.config/nvim"))
vim.opt.packpath:remove(vim.fn.expand("~/.local/share/nvim/site"))

-- append test directory
local test_dir = "/tmp/nvim/replacer"
vim.opt.runtimepath:append(vim.fn.expand(test_dir))
vim.opt.packpath:append(vim.fn.expand(test_dir))

-- install packer
local install_path = test_dir .. "/pack/packer/start/packer.nvim"
local install_plugins = false

if vim.fn.empty(vim.fn.glob(install_path)) > 0 then
    vim.cmd("!git clone https://github.com/wbthomason/packer.nvim " .. install_path)
    vim.cmd("packadd packer.nvim")
    install_plugins = true
end

local function check_clean()
  for _, arg in ipairs(vim.v.argv) do
    if arg == '--clean' then
      vim.g.loaded_remote_plugins = 1
      return
    end
  end
end
check_clean()

local packer = require("packer")

packer.init({
    package_root = test_dir .. "/pack",
    compile_path = test_dir .. "/plugin/packer_compiled.lua",
})

-- install plugins
packer.startup(function(use)
    use("wbthomason/packer.nvim")
    -- use {
    --   'gabrielpoca/replacer.nvim',
    --   commit = "e06a955104ffabac839be7a2b00a3e10e8f59e16"
    -- }
    use 'stefandtw/quickfix-reflector.vim'
    use {
      'ibhagwan/fzf-lua',
      -- optional for icon support
      requires = { 'nvim-tree/nvim-web-devicons' }
    }

    if install_plugins then
        packer.sync()
    end
end)

local ok, replacer = pcall(require, "replacer")
if ok then
  vim.keymap.set('n','<Leader>qf', replacer.run, { desc = "qf replacer activate", nowait = true, silent = true })
end
vim.opt.autochdir = true                    -- Your working directory will always be the same as your working directory
```

**Comment by gabrielpoca** [comment]
@RayZ0rr thank you so much. I don't remember anyone being so helpful in issue reports 🙏 I could replicate the issue, and it seems like it was indeed one of the ones I fixed in my last commit. Can you try it out? I just updated the hash in your config to `8cac117afab0213c1d235255aa4245ea1d06add9` and it worked.

**Comment by RayZ0rr** [comment]
I have checked that the previous issue has disappeared. However, now the quickfix list is not updated after making the change. It still shows the state before the edit was made.

**Comment by gabrielpoca** [comment]
Ok, issue 1 I can solve, but it helps avoid bugs because after you edit the list and save it, you can't edit it again. Do you think it's an issue?
Regarding issue 2, do you mean that if you build another quick fix and run replacer, you see the previous edit buffer?

**Comment by RayZ0rr** [comment]
> 1. The quickfix list closes after saving the quickfix buffer.
> 
> 2. The quickfix list is not updated after making the change. It still shows the state before the edit was made.


Yes, I too think issue 1 can be ignored.

Regarding issue 2, I meant to say that :

1. After changes are saved in the replacer quickfix buffer it closes (as mentioned above this is fine)
2. If I open quickfix buffer again with `:copen` it shows the unchanged quickfix buffer

> Regarding issue 2, do you mean that if you build another quick fix and run replacer, you see the previous edit buffer?

If you build another quickfix buffer the changes are reflected properly without any issue. The "unchanged" quickfix buffer is only shown if you try to open it after making the changes in replacer and before building another one.

Maybe this is kind of an expected behavior and hard to change.

**Comment by gabrielpoca** [comment]
Yeah, that makes sense because it never deletes the original quickfix buffer. But it definitely should, because that buffer is now point to places that have likely been changed

**Comment by gabrielpoca** [comment]
It should be fixed with my latest change. Can you give it a go?

**Comment by RayZ0rr** [comment]
Perfect !

I feel like this has become the most powerful refactoring tool.
